apiVersion: v1
kind: Service
metadata:
  name: transcode-app
spec:
  type: NodePort
  selector:
    app: transcode-app
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
      nodePort: 31001